### ISSUE TITLE
Erreur dans la pagination

### ISSUE THREAD

**Issue by MedKhachira** [liorchamla/formation-symfony#1]
Bonjour Liorchamla,

Je voudrais réutiliser la partie pagination dans mon projet mais j'ai une erreur dans le bouton Previous et Next  
![image](https://user-images.githubusercontent.com/3090574/53549564-c9b60c00-3b34-11e9-832a-d6f3ed6f5fdc.png)

Malgré que le bouton est grisé l'evenement de clique est déclenché et j'ai une erreur dans le route et c'est normal puisque y a pas une page 0.

An exception has been thrown during the rendering of a template ("Offset must be a positive integer or zero, -10 given").

Est ce qu'il me manque un truc dans le JS?
Il existe un bundle knp paginator qui implemente ce mécanisme, pour quoi t'as créé une pagination from scratch?

**Comment by liorchamla** [comment]
J'ai créé une pagination from scratch dans le cadre d'une formation où je voulais initier les gens au concept de service dans Symfony. 

Normalement si tu utilises cette pagination avec la version 4 de bootstrap y a pas de raison que ça ne marche pas.

**Comment by MedKhachira** [comment]
Merci pour ta réponse rapide, par contre la version 4 de bootstrap sert juste pour l'affichage, en fait moi j'utilise boostrap 3 pour mon template et j'ai ajouté dans twig.yaml le thème de boostrap 4 
form_themes: ['bootstrap_4_horizontal_layout.html.twig']. Je te confirme que la pagination fonctionne bien mais seulement lorsque j'arrive sur la page 1 ou la page max (10 dans mon cas) les deux boutons Previous et Next deviennent grisés mais lorsque je clique l’événement est déclenché, pour la page 0 et la page 11. Je vais essayer d'enlever les fichiers js et css dans mon projet et vérifier si c'est lié à la version de boostrap.

**Comment by liorchamla** [comment]
Oui c'est ce que je te dis 😁 si tu prend ma pagination avec des classes bootstrap 4 alors que ton site utilise bootstrap 3, c'est logique que le bouton précédent ou suivant ne se comporte pas correctement .. 😉

**Comment by MedKhachira** [comment]
Effectivement, le problème est dans la version 3 de bootstrap , c'est bizarre que la classe  "disabled" ne fonctionne pas correction dans une balise <li>, j'ai fait un test rapide et j'ai constaté que ce bout de code fonctionne pour bootstrap4 mais pas bootstrap3 : 
------------------------------------------------------------bootstrap3-----------------------------------------------------------
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Pagination</h2>
  <p>The .pagination class provides pagination links:</p>                  
  <ul class="pagination">
    <li class="disabled"><a href="https://www.google.com/">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
  </ul>
</div>

</body>
</html>
------------------------------------------------------------bootstrap4-----------------------------------------------------------
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Pagination</h2>
  <p>To create a basic pagination, add the .pagination class to an ul element. Then add the .page-item to each li element and a .page-link class to each link inside li:</p>                  
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item disabled"><a class="page-link" href="https://www.google.com/">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</div>

</body>
</html>
-----------------------------------------------------------------------------------------------------------------------------------
Du coup pour boostrap 3 le <li> devient grisé mais le clique déclenche par contre dans boostrap 4 le code fonctionne correctement.

Je ne sais pas si c'est un bug dans bootsrap 3.

**Comment by liorchamla** [comment]
Bah c'est pas un bug de Bootstrap 3 c'est que dans Bootstrap 3 c'est surement pas exactement les mêmes classes qu'il faut mettre dans la pagination donc forcément si tu utilises des balises et des classes de Bootstrap 4 alors que le fichier CSS c'est celui de Bootstrap 3 bah ça marche pas.

**Comment by MedKhachira** [comment]
Oui je suis d'accord avec toi mais ici je parle seulement de comportement de la classe [disabled] dans bootsrap 3 et 4.

C'est bon pour moi merci beaucoup Lior j'ai beaucoup apprécié notre échange :+1:
